local set = vim.opt

set.guicursor = ""
set.errorbells = false
set.hidden = true
set.tabstop = 4
set.softtabstop = 4
set.shiftwidth = 4
set.expandtab = true
set.smartindent = true
set.number = true
set.relativenumber = true
set.ignorecase = true
set.smartcase = true
set.swapfile = false
set.backup = false
set.incsearch = true
set.scrolloff = 15
set.splitbelow = true
set.splitright = true
set.termguicolors = true
